#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\DefaultController::index

simpleText:
    path: /simpleText/
    controller: App\Controller\Task9Controller::simpleText