#index:
#    path: /
#    controller: App\Controller\DefaultController::index


simpleText:
    path: /simple_text/
    controller: App\Controller\TaskController::simpleText

JSON:
    path: /json/
    controller: App\Controller\TaskController::jsonAPI

RDRCT:
    path: /my-redirect/{page_site}
    controller: App\Controller\TaskController::goToGoogle
    defaults:
            page_site: google.com

#number_from_get:
#    path: /post/page/{number}
#    controller: App\Controller\TaskController::getNumber
#    defaults:
#      number: 1
#    methods: [GET]
#    requirements:
#      # number: \d+ # только числа
#      # number: ^\d{1,2}$ # числа  от 1 до 99, но попадает 0 и 00
#       number: ([1-9][0-9]?)