#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# comment

index:
    path: /
    controller: App\Controller\DefaultController::index

blog_show:
    path: /blog/{slug}
    controller: App\Controller\BlogController::showAction

simpleText:
    path: /simpleText/
    controller: App\Controller\Task9Controller::simpleText

JSON:
    path: /json/
    controller: App\Controller\Task9Controller::jsonAPI

RDRCT:
    path: /my-redirect/{page_site}
    controller: App\Controller\Task9Controller::goToGoogle
    defaults:
            page_site: google.com

#number_from_get:
#    path: /post/page/{number}
#    controller: App\Controller\Task9Controller::getNumber
#    defaults:
#      number: 1
#    methods: [GET]
#    requirements:
#      # number: \d+ # только числа
#      # number: ^\d{1,2}|100$ # числа  от 1 до 100, но попадает 0 и 00
#       number: ([1-9][0-9]?|100)