#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# comment

index:
    path: /
    controller: App\Controller\DefaultController::index

blog_show:
    path: /blog/{slug}
    controller: App\Controller\BlogController::showAction

simpleText:
    path: /simpleText/
    controller: App\Controller\Task9Controller::simpleText

JSON:
    path: /json/
    controller: App\Controller\Task9Controller::jsonAPI